### ISSUE TITLE
運行 SDK init 閃退

### ISSUE THREAD

**Issue by rik296** [GO-LiFE/GoFIT_SDK_Android#37]
```
2019-11-14 11:35:10.270 28039-28039/com.goyourlife.gofit_demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.goyourlife.gofit_demo, PID: 28039
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.goyourlife.gofit_demo-QvMKe1iKCCsuyHsONcvn_A==/base.apk"],nativeLibraryDirectories=[/data/app/com.goyourlife.gofit_demo-QvMKe1iKCCsuyHsONcvn_A==/lib/arm64, /system/lib64]]] couldn't find "libsdk-lib.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.goyourlife.gofitsdk.GoFITSdk.<clinit>(GoFITSdk.java:53)
        at com.goyourlife.gofitsdk.GoFITSdk.getInstance(Unknown Source:0)
        at com.goyourlife.gofit_demo.MainActivity.onPreferenceClick(MainActivity.java:228)
        at android.preference.Preference.performClick(Preference.java:1250)
        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:262)
        at android.widget.AdapterView.performItemClick(AdapterView.java:362)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
        at android.widget.AbsListView$7.run(AbsListView.java:6612)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7037)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by rik296** [comment]
gradle 設定需要調整
最外層的 build.gradle：
`classpath 'com.android.tools.build:gradle:3.2.1'`

gradle-wrapper.properties 這個檔案
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`

![螢幕快照 2019-11-14 11 20 39](https://user-images.githubusercontent.com/16934269/68825181-2f065900-06d4-11ea-885c-7c693e967c37.png)

![螢幕快照 2019-11-14 11 20 46](https://user-images.githubusercontent.com/16934269/68825175-2c0b6880-06d4-11ea-8e73-cf211ccc3ea5.png)

**Comment by libo1409** [comment]
这样修改后 还是闪退呢

**Comment by rik296** [comment]
Hi，您好，請問您閃退的 logcat 也是跟上面相同嗎？還是遇到其他的狀況呢？

**Comment by libo1409** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file `"/data/app/com.goyourlife.gofit_demo-EFGgMSmmMnbIUgV2e9efmA==/base.apk"],nativeLibraryDirectories=[/data/app/com.goyourlife.gofit_demo-EFGgMSmmMnbIUgV2e9efmA==**/lib/x86,**` /system/lib]]] couldn't find "libsdk-lib.so"

lib/x86

**Comment by rik296** [comment]
可以試試看在 android studio 上方的 `File` -> `Invalidate caches / restart`
若還是無法解決，您若願意打包整個專案檔上傳到網路空間，讓我這邊可以下載幫您看看是哪邊還需要調整 🙏

**Comment by libo1409** [comment]
[GoFIT_SDK_Android-1.4_2018-11-28.zip](https://github.com/GO-LiFE/GoFIT_SDK_Android/files/3872672/GoFIT_SDK_Android-1.4_2018-11-28.zip)

**Comment by rik296** [comment]
@libo1409 您好，我將您的 app 中的 build.gradle 修改為以下即可運行：
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.goyourlife.gofit_demo"
        minSdkVersion 18
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

allprojects {
    repositories {
        flatDir {
            dirs 'libs'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation (name:'GoFIT_SDK-release', ext:'aar')
}
```

您可以參考看看，另外我們的 lib 有更新版本，
https://github.com/GO-LiFE/GoFIT_SDK_Android/releases/tag/v1.5_2019-07-23
若您尚未更新，亦可一並更新，謝謝！

**Comment by libo1409** [comment]
这个demo是只能在真机上测试吗 模拟器闪退  真机就不会

**Comment by rik296** [comment]
是的，我們的 SDK 為了讓客戶能快速應用到產品端，只有開發 device 版本，沒有 simulator 的版本
